// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Format } from './Format'
import type { SqlType } from './SqlType'

export interface CanvasStoreColumnMetaData {
  humanizedHeader: string | null
  sqlHeader: string | null
  formula: string | null
  formulaError: string | null
  sqlType: SqlType | null
  hidden: boolean
  format: Format | null
}
