// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasStoreColumnMetaData } from './CanvasStoreColumnMetaData'
import type { StoreType } from './StoreType'

export interface CanvasStoreMetaData {
  sourceKey: string
  title: string
  allColumns: Array<string>
  visibleColumns: Array<string>
  columnMeta: Record<string, CanvasStoreColumnMetaData>
  storeType: StoreType
  compileError: string | null
  validSql: boolean
  formulaColumnsDisabled: string | null
  rowCount: bigint | null
  nonFilterRowCount: bigint | null
}
