// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartConfig } from './ChartConfig'

export interface ChartSlice {
  storeId: string
  config: ChartConfig
  aggregatonStoreId: string | null
}
