// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ChartMargin {
  top: number | null
  bottom: number | null
  left: number | null
  right: number | null
  pad: number | null
  xTickAngle: number | null
  yTickAngle: number | null
  maxTickLength: number | null
  yAxisMinimum: number | null
  yAxisMaximum: number | null
}
