// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartTemplateSeriesAggregation } from './ChartTemplateSeriesAggregation'

export interface ChartTemplateSeries {
  columnName: string
  aggregation: ChartTemplateSeriesAggregation | null
}
