// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Format } from './Format'
import type { LineDash } from './LineDash'
import type { LineShape } from './LineShape'

export interface ChartDataSeriesConfig {
  secondYAxis: boolean
  lineShape: LineShape
  lineDash: LineDash
  format: Format
}
