// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AggregationField } from './AggregationField'
import type { ChartConfig } from './ChartConfig'
import type { ValueField } from './ValueField'

export interface ChartContext {
  elementId: string
  chartConfig: ChartConfig
  title: string | null
  storeId: string
  rowField: AggregationField | null
  valueFields: Array<ValueField> | null
}
