// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormulaColumn } from './FormulaColumn'

export type ColumnType =
  | 'data'
  | { formula: { formula: string } }
  | { formulaV2: { formula: FormulaColumn } }
