// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleSlice } from './RuleSlice'

export interface CustomFilterSlice {
  rules: Array<RuleSlice>
  derivedLogicDisplay: string | null
}
