// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RightClickMenu } from './RightClickMenu'
import type { SqlEditorQueryMeta } from './SqlEditorQueryMeta'

export enum CustomReactEventType {
  ToggleSqlEditor = 'toggleSqlEditor',
  SetRightClickMenu = 'setRightClickMenu',
}
export type ToggleSqlEditorEvent = {
  type: CustomReactEventType.ToggleSqlEditor
  extra: SqlEditorQueryMeta
}
export type SetRightClickMenuEvent = {
  type: CustomReactEventType.SetRightClickMenu
  extra: RightClickMenu
}
export type CustomReactEvent = ToggleSqlEditorEvent | SetRightClickMenuEvent
