// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RightClickMenu } from './RightClickMenu'
import type { SqlEditorQueryMeta } from './SqlEditorQueryMeta'

export type CustomReactEvent =
  | { type: 'toggleSqlEditor'; extra: SqlEditorQueryMeta }
  | { type: 'setRightClickMenu'; extra: RightClickMenu }
