// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CanvasStoreMetaData } from './CanvasStoreMetaData'

export interface DataStorePayload {
  storeId: string
  columnCount: number
  rowCount: number
  payload: Array<Array<string>>
  metaData: CanvasStoreMetaData
}
