// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DropdownOption } from './DropdownOption'

export interface Dropdown {
  prompt: string
  options: Array<DropdownOption>
  highlighted_option: string | null
}
