// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from './Element'
import type { ElementSize } from './ElementSize'
import type { Model } from './Model'
import type { Point } from './Point'
import type { Text } from './Text'

export interface ElementAttributes {
  element: Element
  position: Point
  size: ElementSize
  z_index: number
  title: Text | null
  hidden: boolean
  model: Model | null
}
