// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterConfig } from './FilterConfig'
import type { FilterVariableValue } from './FilterVariableValue'

export interface FilterState {
  type: 'FilterState'
  filters: Array<FilterConfig>
  values: Record<string, FilterVariableValue>
  default_values_v2: Record<string, FilterVariableValue>
  initial_search_query: string | null
}
