// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnMetaData } from './ColumnMetaData'
import type { CustomFilter } from './CustomFilter'
import type { MetaDataVersion } from './MetaDataVersion'
import type { Sort } from './Sort'
import type { SqlDialect } from './SqlDialect'
import type { SqlState } from './SqlState'
import type { StoreType } from './StoreType'

export interface MetaData {
  sourceKey: string
  title: string
  columns: Array<string>
  rows: Array<string>
  columnMeta: Record<string, ColumnMetaData>
  storeType: StoreType
  sqlDialect: SqlDialect | null
  customSqlQuery: string | null
  filter: CustomFilter
  draftFilter: CustomFilter | null
  sqlState: SqlState | null
  sorts: Array<Sort>
  compileError: string | null
  version: MetaDataVersion
}
