// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from './Point'
import type { PositionTarget } from './PositionTarget'

export type PositionType =
  | 'Absolute'
  | { Relative: { position: Point; target: PositionTarget } }
  | { Sticky: { target: PositionTarget } }
