// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SelectValues } from './SelectValues'

export interface SelectUniqueValues {
  stores: Record<string, SelectValues>
}
