// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Spreadsheet {
  _deprecated_element_id: string
  custom_column_widths: Record<string, number>
  _deprecated_custom_column_widths_v1: Record<string, number>
  custom_row_heights: Record<string, number>
  hidden_columns: Array<string>
  data_source_key: string
  empty_rows_enabled: boolean
}
