// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SqlEditorQueryMeta {
  storeId: string | null
  spreadsheetTitle: string
  sqlQuery: string
  readOnlyText: string | null
  saveEnabled: boolean
  isDirty: boolean
  parserError: string | null
}
