// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartTemplateFilter } from './ChartTemplateFilter'
import type { ChartTemplateSeries } from './ChartTemplateSeries'
import type { ChartTemplateSeriesAggregation } from './ChartTemplateSeriesAggregation'
import type { ChartType } from './ChartType'
import type { DateAggregation } from './DateAggregation'
import type { Pivot } from './Pivot'
import type { SqlDialect } from './SqlDialect'

export type TemplateConfig =
  | {
      type: 'chart'
      name: string
      databaseName: string | null
      schemaName: string
      tableName: string
      warehouseAuthId: string
      sqlDialect: SqlDialect
      domainColumn: string
      domainGroupBy: string | null
      chartType: ChartType
      stacks: Array<string> | null
      stackBy: string | null
      series: Array<ChartTemplateSeries>
      filters: Array<ChartTemplateFilter>
      pivot: Pivot | null
    }
  | {
      type: 'cohort'
      name: string
      databaseName: string | null
      schemaName: string
      tableName: string
      warehouseAuthId: string
      sqlDialect: SqlDialect
      cohortColumnName: string
      cohortGroupBy: DateAggregation
      timestampColumnName: string
      valueColumnName: string
      aggregation: ChartTemplateSeriesAggregation
    }
