// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point } from './Point'
import type { RotationOrigin } from './RotationOrigin'
import type { TextAlign } from './TextAlign'
import type { TextValue } from './TextValue'
import type { VerticalAlign } from './VerticalAlign'

export interface Text {
  inner_value: TextValue
  data_store_id: string | null
  size: Point
  font_size: number
  rotation: number
  rotation_origin: RotationOrigin
  align: TextAlign
  vertical_align: VerticalAlign
  font_family: string
  vertical_padding: number
  horizontal_padding: number
  hyperlink: string | null
}
