// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetaDataSlice } from './MetaDataSlice'

export interface UpdateDataStoreMore {
  storeId: string
  columnCount: number
  rowCount: number
  payload: Array<string>
  kind: string
  metaData: MetaDataSlice
}
