// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartFilterCondition } from './ChartFilterCondition';

export interface ChartTemplateFilter {
    columnName: string;
    condition: ChartFilterCondition;
}
