// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Component {
    component: string;
    config: string;
    store_id: string;
}
