// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DateAggregation =
    | 'hour'
    | 'hourofday'
    | 'dayofweek'
    | 'month'
    | 'quarter'
    | 'year'
    | 'weeknumber'
    | 'yearweeknumber'
    | 'yearweekdate'
    | 'yearmonth'
    | 'yearmonthnumber'
    | 'yearquarter'
    | 'yearmonthday';
