// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DraftElementKind } from './DraftElementKind';

export interface DraftElement {
    kind: DraftElementKind;
}
