// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Order } from './Order';

export interface EmbedSort {
    columnId: string;
    order: Order;
}
