// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartEmbed } from './ChartEmbed';
import type { ComponentEmbed } from './ComponentEmbed';
import type { SpreadsheetEmbed } from './SpreadsheetEmbed';
import type { TextEmbed } from './TextEmbed';

export type EmbedElementType =
    | ({ type: 'chart' } & ChartEmbed)
    | ({ type: 'spreadsheet' } & SpreadsheetEmbed)
    | ({ type: 'text' } & TextEmbed)
    | ({ type: 'component' } & ComponentEmbed);
