// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterSourceTable } from './FilterSourceTable';

export type FilterType =
    | { type: 'date' }
    | { type: 'search' }
    | {
          type: 'select';
          storeId: string | null;
          sourceStoreId: string | null;
          sourceTable: FilterSourceTable | null;
          valuesColumn: string | null;
          labelsColumn: string | null;
      }
    | {
          type: 'scope';
          storeId: string | null;
          sourceStoreId: string | null;
          sourceTable: FilterSourceTable | null;
          valuesColumn: string | null;
          labelsColumn: string | null;
          scopeName: string | null;
      };
