// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbedSort } from './EmbedSort';
import type { FilterVariableValue } from './FilterVariableValue';

export interface GetCanvasEmbedRequest {
    canvasId: string;
    warehouseAuthId: string;
    scopedVariables: Record<string, FilterVariableValue> | null;
    urlVariables: Record<string, string> | null;
    sorts: Record<string, EmbedSort>;
}
