// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnMeta } from './ColumnMeta';

export interface GetTableModelDataResponse {
    columns: Array<string>;
    columnMeta: Record<string, ColumnMeta>;
    sql: string | null;
}
