// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GlobalFilter =
    | { type: 'DateFilter'; variable: string }
    | { type: 'Search'; variable: string }
    | { type: 'MultiSelect'; variable: string };
