// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PositionTarget =
    | { Element: { element_id: string } }
    | { SpreadsheetCell: { element_id: string; column: string; row: string } };
