// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterVariableValue } from './FilterVariableValue';

export interface ReturnDownloadData {
    title: string;
    query: string;
    dataSourceKey: string;
    hiddenColumns: Array<string>;
    variables: Record<string, FilterVariableValue>;
    headers: Record<string, string>;
}
