// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataPayload } from './DataPayload';

export interface SetDataPayload {
    payloads: Array<DataPayload>;
}
