// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetaPayload } from './MetaPayload';

export interface SetMetaPayload {
    payloads: Array<MetaPayload>;
}
