// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpreadsheetDisplayExtras } from './SpreadsheetDisplayExtras';

export interface SpreadsheetSlice {
    hiddenColumns: Array<string>;
    dataSourceKey: string;
    displayExtras: SpreadsheetDisplayExtras;
}
