// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Format } from './Format';

export interface TextValue {
    format: Format;
    raw_value: string;
    computed_value: string;
    formatted_value: string;
}
