// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartMargin } from './ChartMargin';
import type { ChartType } from './ChartType';
import type { ColorDimension } from './ColorDimension';
import type { ColorTheme } from './ColorTheme';
import type { DateAggregation } from './DateAggregation';
import type { SeriesConfig } from './SeriesConfig';
import type { SeriesFormat } from './SeriesFormat';
import type { StackType } from './StackType';
import type { SummarizationStrategy } from './SummarizationStrategy';
import type { Trendline } from './Trendline';

export interface UpdateChartConfig {
    elementId: string;
    chartType: ChartType;
    domainColumnId: string;
    seriesColumnIds: Array<string>;
    stackType: StackType | null;
    title: string;
    seriesFormats: Array<SeriesFormat> | null;
    cumulative: boolean;
    xAxisTitle: string | null;
    yAxisTitle: string | null;
    dateAggregation: DateAggregation | null;
    seriesSummarizations: Record<string, SummarizationStrategy> | null;
    trendline: Trendline | null;
    colorTheme: ColorTheme | null;
    colorDimension: ColorDimension | null;
    horizontal: boolean;
    showBarTotals: boolean;
    highlightColumnId: string | null;
    margin: ChartMargin | null;
    seriesConfigs: Record<string, SeriesConfig>;
    colorBackgroundColumnId: string | null;
    targets: Array<string>;
    fullWidth: boolean;
}
