// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnSortStrategy } from './ColumnSortStrategy'
import type { DateAggregation } from './DateAggregation'
import type { OrderingStrategy } from './OrderingStrategy'

export interface AggregationField {
  id: string
  label: string
  orderingStrategy: OrderingStrategy
  sortById: string
  dateAggregation: DateAggregation | null
  columnSortStrategy: ColumnSortStrategy | null
}
