// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextValue } from './TextValue';

export interface Cell {
    value: TextValue;
}
