// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateAggregation } from './DateAggregation';

export type ChartAggregation = { type: 'date'; date_aggregation: DateAggregation } | { type: 'value' };
