// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartDataSeriesConfig } from './ChartDataSeriesConfig'
import type { ChartMargin } from './ChartMargin'
import type { ChartType } from './ChartType'
import type { ColorBackground } from './ColorBackground'
import type { ColorDimension } from './ColorDimension'
import type { ColorTheme } from './ColorTheme'
import type { DateAggregation } from './DateAggregation'
import type { Format } from './Format'
import type { Highlight } from './Highlight'
import type { SeriesFormat } from './SeriesFormat'
import type { StackType } from './StackType'
import type { Trendline } from './Trendline'
import type { VariableCategory } from './VariableCategory'

export interface ChartData {
  chartType: ChartType
  labels: Array<string>
  seriesNames: Array<string>
  seriesColumnIds: Array<string>
  seriesFormat: Format
  domainFormat: Format
  domainCategory: VariableCategory | null
  values: Array<Array<string>>
  domainLabel: string
  stackType: StackType | null
  horizontal: boolean
  xAxisTitle: string | null
  yAxisTitle: string | null
  seriesFormats: Array<SeriesFormat> | null
  trendline: Trendline | null
  colorTheme: ColorTheme
  colorDimension: ColorDimension
  lastDomainLabelIncomplete: boolean
  showBarTotals: boolean
  dateAggregation: DateAggregation | null
  highlight: Highlight | null
  colorBackground: ColorBackground | null
  margin: ChartMargin | null
  error: string | null
  seriesConfigs: Record<string, ChartDataSeriesConfig>
}
