// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateAggregation } from './DateAggregation';
import type { ValueField } from './ValueField';

export interface CohortOptions {
    cohortField: string | null;
    cohortAggregation: DateAggregation | null;
    timestampField: string | null;
    valueField: ValueField | null;
}
