// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnType } from './ColumnType';
import type { Format } from './Format';

export interface ColumnMetaData {
    userAdded: boolean;
    header: string | null;
    userAddedHeader: string | null;
    columnType: ColumnType;
    format: Format | null;
    sqlType: string | null;
    hidden: boolean | null;
}
