// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentPinStatus } from './CommentPinStatus'
import type { PositionType } from './PositionType'

export interface CommentPin {
  pin_id: number
  pin_number: number
  status: CommentPinStatus
  position_type: PositionType
}
