// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cell } from './Cell';
import type { Component } from './Component';
import type { Grid } from './Grid';

export interface ComponentEmbed {
    component: Component;
    grid: Grid<Cell>;
}
