// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rule } from './Rule'

export interface CustomFilter {
  rules: Array<Rule>
  derivedLogicDisplay: string | null
}
