// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartType } from './ChartType';

export type DraftElementKind =
    | { kind: 'chart'; chart_type: ChartType }
    | { kind: 'table' }
    | { kind: 'join' }
    | { kind: 'pivot' };
