// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Text } from './Text';

export interface DropdownOption {
    key: string;
    value: string;
    value_text: Text;
}
