// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chart } from './Chart';
import type { CommentPin } from './CommentPin';
import type { Component } from './Component';
import type { Cursor } from './Cursor';
import type { DraftElement } from './DraftElement';
import type { FormulaInput } from './FormulaInput';
import type { Image } from './Image';
import type { Spreadsheet } from './Spreadsheet';
import type { Text } from './Text';

export type Element =
    | { Chart: Chart }
    | { CommentPin: CommentPin }
    | { Cursor: Cursor }
    | { FormulaInput: FormulaInput }
    | { Image: Image }
    | { Spreadsheet: Spreadsheet }
    | { DraftElement: DraftElement }
    | { Text: Text }
    | { Component: Component };
