// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ElementPosition =
  | { type: 'top' }
  | { type: 'hidden' }
  | { type: 'oldUi' }
  | { type: 'remain' }
  | { type: 'above'; element: string }
  | { type: 'left'; element: string }
  | { type: 'below'; element: string }
  | { type: 'right'; element: string }
