// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementAttributes } from './ElementAttributes'
import type { MetaData } from './MetaData'

export interface ElementModel {
  element: ElementAttributes
  parentElements: Array<ElementAttributes>
  metas: Array<MetaData>
}
