// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementSlice } from './ElementSlice'
import type { Model } from './Model'

export interface ElementAttributesSlice {
  element: ElementSlice
  title: string | null
  hidden: boolean
  model: Model | null
}
