// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartEmbed } from './ChartEmbed';
import type { DataPayload } from './DataPayload';
import type { TextEmbed } from './TextEmbed';

export type EmbedElementType =
    | ({ type: 'chart' } & ChartEmbed)
    | ({ type: 'spreadsheet' } & DataPayload)
    | ({ type: 'text' } & TextEmbed);
