// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmbedElementType } from './EmbedElementType';

export interface EmbedElement {
    elementType: EmbedElementType;
    title: string | null;
}
