// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterByConditionSlice =
  | { type: 'IsEmpty' }
  | { type: 'IsNotEmpty' }
  | { type: 'IsTrue' }
  | { type: 'IsFalse' }
  | { type: 'TextContains'; operand: string }
  | { type: 'TextDoesNotContain'; operand: string }
  | { type: 'TextStartsWith'; operand: string }
  | { type: 'TextEndsWith'; operand: string }
  | { type: 'TextIsOneOfMultiple'; operand: Array<string> }
  | { type: 'TextIsNotOneOfMultiple'; operand: Array<string> }
  | { type: 'DateIs'; operand: string }
  | { type: 'DateIsBefore'; operand: string; exclusive: boolean }
  | { type: 'DateIsAfter'; operand: string; exclusive: boolean }
  | { type: 'DateIsBetween'; lower: string; higher: string; exclusive: boolean }
  | { type: 'GreaterThan'; operand: string }
  | { type: 'GreaterThanOrEqualTo'; operand: string }
  | { type: 'LessThan'; operand: string }
  | { type: 'LessThanOrEqualTo'; operand: string }
  | { type: 'IsEqualTo'; operand: string }
  | { type: 'IsNotEqualTo'; operand: string }
  | { type: 'IsEqualToRaw'; operand: string; quoted: boolean }
  | { type: 'IsNotEqualToRaw'; operand: string; quoted: boolean }
  | { type: 'IsBetween'; lower: string; higher: string }
  | { type: 'IsNotBetween'; lower: string; higher: string }
  | { type: 'CustomSql'; value: string }
