// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterType } from './FilterType'

export interface FilterConfig {
  filterId: string
  variable: string
  label: string | null
  icon: string | null
  filterType: FilterType
}
