// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementOrder } from './ElementOrder'
import type { EmbedElement } from './EmbedElement'

export interface GetCanvasEmbedResponse {
  elementOrder: ElementOrder
  elements: Record<string, EmbedElement>
}
