// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementModel } from './ElementModel';

export interface GetChartDataBody {
    element: ElementModel;
    saved_model_id: string;
}
