// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterVariableValue } from './FilterVariableValue';

export interface GetCanvasEmbedRequest {
    canvasId: string;
    warehouseAuthId: string;
    variables: Record<string, FilterVariableValue> | null;
}
