// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface GetElementResponse {
    query: string;
    hiddenColumns: Array<string>;
    columnHeaders: Record<string, string>;
}
