// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Grid<T> {
    data: Array<T>;
    row_count: number;
    column_count: number;
}
