// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnMetaDataSlice } from './ColumnMetaDataSlice';
import type { CustomFilter } from './CustomFilter';
import type { SqlEditorQueryMeta } from './SqlEditorQueryMeta';
import type { SqlStateSlice } from './SqlStateSlice';
import type { StoreType } from './StoreType';

export interface MetaDataSlice {
    sourceKey: string;
    title: string;
    columns: Array<string>;
    columnMeta: Record<string, ColumnMetaDataSlice>;
    storeType: StoreType;
    filter: CustomFilter;
    draftFilter: CustomFilter | null;
    sqlState: SqlStateSlice | null;
    sqlEditorState: SqlEditorQueryMeta | null;
    compileError: string | null;
}
