// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AggregationField } from './AggregationField'
import type { ValueField } from './ValueField'

export interface PivotContext {
  title: string
  storeId: string
  elementId: string
  sourceId: string
  rowFields: Array<AggregationField>
  columnFields: Array<AggregationField>
  valueFields: Array<ValueField>
}
