// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RightClickMenu =
  | { type: 'Blank' }
  | {
      type: 'SpreadsheetColumn'
      options: {
        elementId: string
        columnIndex: number
        columnId: string
        selectedColumnIds: Array<string> | null
        formulaColumnsEnabled: boolean
        validSql: boolean
        filtersEnabled: boolean
        isFormulaColumn: boolean
        dataStoreId: string
        header: string | null
      }
    }
