// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleFilter } from './RuleFilter'

export interface Rule {
  columnId: string
  name: string
  filter: RuleFilter
}
