// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleFilterSlice } from './RuleFilterSlice';

export interface RuleSlice {
    columnId: string;
    name: string;
    filter: RuleFilterSlice;
}
