// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Format } from './Format'

export interface SelectValues {
  values: Array<[string, string]>
  labelFormat: Format | null
  valueFormat: Format | null
}
