// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataStorePayload } from './DataStorePayload'

export interface SetBulkPayload {
  payloads: Array<DataStorePayload>
}
