// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShowCanvasErrorType } from './ShowCanvasErrorType';

export interface ShowCanvasError {
    title: string;
    message: string;
    notificationType: ShowCanvasErrorType;
}
