// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetaData } from './MetaData'

export interface SpreadsheetEmbed {
  data: Array<Array<string>>
  metaData: MetaData
}
