// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnarySqlFunctions } from './UnarySqlFunctions';

export type SqlFormula = { unarySqlFunction: { source_id: string; column_id: string; function: UnarySqlFunctions } };
