// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SqlQuerySlice } from './SqlQuerySlice';

export interface SqlStateSlice {
    query: SqlQuerySlice;
    refs: Array<string>;
}
