// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface UniqueValuesOptions {
    valuesColumn: string | null;
    labelsColumn: string | null;
}
