// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetDataPayload } from './SetDataPayload'
import type { SetMetaPayload } from './SetMetaPayload'

export type UpdateDataStore =
  | ({ kind: 'setData' } & SetDataPayload)
  | ({ kind: 'setMeta' } & SetMetaPayload)
