// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayStrategy } from './DisplayStrategy';
import type { SummarizationStrategy } from './SummarizationStrategy';

export interface ValueField {
    id: string;
    label: string;
    summarizationStrategy: SummarizationStrategy;
    displayStrategy: DisplayStrategy;
}
