name: Build

on:
  push:
    paths:
      - "react/**"
      - ".github/**"

jobs:
  run-builds:
    name: Run builds
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install React dependencies
        working-directory: ./react
        run: npm ci

      - name: Run React build
        working-directory: ./react
        run: npm run build

      - name: Run React build web
        working-directory: ./react
        run: npm run build-web