name: Publish Node.js NPM Package

on:
  push:
    paths:
      - "canvas-embed-node/**"
    branches:
      - main

jobs:
  publish:
    name: Publish Node.js NPM Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: "20.x"
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        working-directory: canvas-embed-node
        run: npm install

      - name: Increment Version
        working-directory: canvas-embed-node
        run: echo "NPM_PACKAGE_VERSION=$(npm version patch)" >> $GITHUB_ENV

      - name: Commit Version Increment
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add canvas-embed-node/package.json canvas-embed-node/package-lock.json
          git commit -m "${{env.NPM_PACKAGE_VERSION}}" -a

      - name: Build
        working-directory: canvas-embed-node
        run: npm run build

      - name: Publish to NPM
        working-directory: canvas-embed-node
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Push Changes
        run: git push
