name: Publish React NPM Package

on:
  push:
    paths:
      - "react/**"
    branches:
      - main

jobs:
  publish:
    name: Publish React NPM Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: "20.x"
          registry-url: https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Install Dependencies
        working-directory: react
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Increment Version
        working-directory: react
        run: npm version patch # You can use "minor" or "major" as well

      - name: Commit Version Increment
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add react/package.json react/package-lock.json
          git commit -m "Bump version" -a

      - name: Build
        working-directory: react
        run: npm run build

      - name: Publish to NPM
        working-directory: react
        run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Push Changes
        run: git push
