name: Publish React to S3 distro

on:
  push:
    paths:
      - "react/**"
    # branches:
    #   - main

jobs:
  publish:
    name: Publish bundle to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: "20.x"
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        working-directory: react
        run: npm install

      - name: Build
        id: build
        working-directory: react
        run: npm run build

      - uses: jakejarvis/s3-sync-action@master
        if: steps.build.outcome == 'success'
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_EMBED_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: "us-west-2"
          SOURCE_DIR: "react/dist"
